# In our task, we operate under the assumption of utilizing AWS Secret Manager to manage environment variables.
firearc:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: $(SF_ACCOUNT)
      user: $(DBT_USER)
      password: $(DBT_PASSWORD)
      database: FIREARC
      warehouse: COMPUTE_WH
      role: ACCOUNTADMIN
      schema: CORE
